app:
  build: .
  command: ruby app.rb
  ports:
    - "4567"
  links:
    - redis
  volumes:
    - ".:/app"
  environment:
    VIRTUAL_HOST: panda.docker

redis:
  image: redis:latest
  ports:
    - "6379"
  environment:
    VIRTUAL_HOST: redis.docker